name: bob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install dependencies
        working-directory: python-greetings
        run: |
          echo "Starting dependency installation..."
          pip3 install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete greetings-app-dev || true

      - name: Start application
        working-directory: python-greetings
        run: pm2 start app.py --name greetings-app-dev -- --port 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Run tests on Dev
        run: |
          echo "Running tests on Dev environment"
          tests-on-dev

  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging environment"
          deploy-to-staging

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - name: Run tests on Staging
        run: |
          echo "Running tests on Staging environment"
          tests-on-staging

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - name: Deploy to Preprod
        run: |
          echo "Deploying to Preprod environment"
          deploy-to-preprod

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Run tests on Preprod
        run: |
          echo "Running tests on Preprod environment"
          tests-on-preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod environment"
          deploy-to-prod

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Run tests on Prod
        run: |
          echo "Running tests on Prod environment"
          tests-on-prod
