name: bob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Clone course-js-api-framework repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Install dependencies
        working-directory: python-greetings
        run: |
          echo "Starting dependency installation..."
          pip3 install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Stop existing service
        working-directory: python-greetings
        run: | 
            pm2 delete "greetings-app-DEV"
            if ($?) { Write-Host "Service stopped successfully" } else { Write-Host "Service not found, continuing..." }
            exit 0
      - name: Start application
        working-directory: python-greetings
        run: pm2 start -f app.py --name greetings-app-dev --interpreter python --env PORT=7001

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Installing dependencies
        working-directory: course-js-api-framework
        run: npm install
      - name: Set environment URL
        working-directory: course-js-api-framework
        run: |
          echo "GREETINGS_APP_DEV_URL=http://localhost:7001" >> .env
          cat .env
      - name: Running test
        working-directory: course-js-api-framework
        run: npm run greetings greetings-app-dev
        
  deploy-to-staging:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete "greetings-app-staging" && set "errorlevel=0" 
      - name: Start application
        run: pm2 start -n "greetings-app-staging" app.py -- 7002

  tests-on-staging:
    runs-on: self-hosted
    needs: deploy-to-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Installing dependencies
        run: npm install
      - name: Running test
        run: npm run greetings greetings_staging

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete "greetings-app-preprod" && set "errorlevel=0" 
      - name: Start application
        run: pm2 start -n "greetings-app-preprod" app.py -- 7003

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Installing dependencies
        run: npm install
      - name: Running test
        run: npm run greetings greetings_preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing service
        run: pm2 delete "greetings-app-prod" && set "errorlevel=0" 
      - name: Start application
        run: pm2 start -n "greetings-app-prod" app.py -- 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework

      - name: Installing dependencies
        run: npm install
      - name: Running test
        run: npm run greetings greetings_prod
